config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  root "static_pages#home"
  
  get '/home', to: 'static_pages#home'

  get '/about', to: 'static_pages#about'
  
  get '/signup', to: 'users#new'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  post '/users/:user_id/drawers/:id', to: 'drawers#update'
  
  resources :users do 
  resources :recipes
  end
  
  resources :users do
  resources :api_requests
  end
    
  resources :users do 
  resources :drawers
  end
  
  resources :drawers do 
  resources :drawer_ingredients
  end 
  
  resources :users do 
  resources :drawers do 
    get 'go_shopping'
  resources :recipes do
    get 'execute'
      end
    end
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  before_action :check_logged_in, only: :about
  
  def home 
  end
  
  def about
  end
  
  private

  def check_logged_in
      if current_user.nil?
      flash[:danger] = "Please Signup/Log in first."
      redirect_to root_path
      else
      end
    end 

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<br><br>
  <% if current_user.nil? %>
  <%= link_to "Sign up", signup_path %> or <%= link_to "log in", login_path %>
  for the best cooking management experience of your life!
  <% else %>
  
<br><br>
Hey, <%= link_to "#{current_user.email}", current_user %>! Welcome to the beautiful world of a 
  well-managed kitchen ;)
  
<br><br><%= link_to "New recipe?", new_user_recipe_path(current_user, @recipe) %>
<% end %>

  
  