config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  root "static_pages#home"
  
  get '/home', to: 'static_pages#home'

  get '/about', to: 'static_pages#about'
  
  get '/signup', to: 'users#new'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  post '/users/:user_id/drawers/:id', to: 'drawers#update'
  
  resources :users do 
  resources :recipes
  end
  
  resources :users do
  resources :api_requests
  end
    
  resources :users do 
  resources :drawers
  end
  
  resources :drawers do 
  resources :drawer_ingredients
  end 
  
  resources :users do 
  resources :drawers do 
    get 'go_shopping'
  resources :recipes do
    get 'execute'
      end
    end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  
    has_many :drawers, dependent: :destroy 
    has_many :ingredients, dependent: :destroy
    has_many :recipes
    after_create :create_drawer
  
  #attr_accessor :remember_token
  
    validates :name, presence: true, length: { minimum: 5 } 
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 }, 
                                format: { with: VALID_EMAIL_REGEX },
                                 uniqueness: { case_sensitive: false}
                                 
    has_secure_password
  
    validates :password, presence: true, length: { minimum: 6 }
    
    def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
    end
    
    
    def create_drawer
      self.drawers.create
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :check_logged_in, only: [:edit, :show, :update]
  before_action :check_if_authorized, only: [:edit, :show, :update]
  
  def show
    @user = User.find(params[:id])
    @drawer = Drawer.find_by(id: current_user.drawers.first.id)
  end
  
  def new
    @user = User.new
  end

  def create
       @user = User.new user_params
    if @user.save
     log_in @user
      flash[:info] = "Please check your email to activate your account."
      redirect_to @user
    else
      flash[:danger] = "Something went wrong. Please try again."
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
    flash.now[:success] = "Profile updated"
    redirect_to @user
    else
      render 'edit'
  
    end
  end
  
    private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
    
    def check_logged_in
      if current_user.nil?
      flash[:danger] = "Please Signup/Log in first."
      redirect_to root_path
      else
      end
    end 
    
    def check_if_authorized
      @user = User.find_by(id: params[:id])
      if @user == current_user
      else
        redirect_to root_path
        flash[:danger] = "It doesn't seem you are authorized to take this action."
      end
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
    
    </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<br>
<%= @user.name %><br><br>
<%= link_to "New recipe?", new_user_recipe_path(@user, @recipe) %>
<% i=DrawerIngredient.of @drawer %>
<% if !(i.nil?) && !(i.empty?) %>
|| 
<%= link_to "Go shopping!", user_drawer_go_shopping_url(drawer_id: "#{@drawer.id}", 
 user_id: "#{current_user.id}" ) %> 
<% end %>
<br><br>

<%= link_to "#{@drawer.my_inventory}", edit_user_drawer_path(@user, @drawer) %>: <br>
<% i.order(quantity: :desc).each do |x| %>
<%= x.ingredient_name %>: 
<%= x.quantity %> | 
<% end %><br>

<br><br>

My recipes:<br><br>

      <% current_user.recipes.all.each do |c| %>
  
  <span style="font-size: 21px;">
  <%= c.title  %> </span>
  (
  <%= link_to "View recipe page", user_recipe_path(current_user, c) %> | 
  <%= link_to "Edit this recipe", edit_user_recipe_path(current_user, c) %>
  )<br>
      
  <% Ingredient.scope(c).each do |x|  %>
  <%= "#{x.name}: #{x.quantity} | " %>
  <% end %>
  <br>

  <%# c.ingredients.each do |x| %>
  <%# ii = DrawerIngredient.find_by(ingredient_name: x.name) %>
  <%# if x.quantity>=ii.quantity %>
<br><span style="border: 1px solid blue; padding: 3px; margin: 8px; border-radius: 2px;">
<%= link_to "Execute+", user_drawer_recipe_execute_path(drawer_id: "#{@drawer.id}", 
recipe_id: "#{c.id}", user_id: "#{current_user.id}" ) %></span><br><br><br>
  <%# else %>

  <%# end %>
  <%# end %>
      <% end %>