config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  root "static_pages#home"
  
  get '/home', to: 'static_pages#home'

  get '/about', to: 'static_pages#about'
  
  get '/signup', to: 'users#new'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  post '/users/:user_id/drawers/:id', to: 'drawers#update'
  
  resources :users do 
  resources :recipes
  end
  
  resources :users do
  resources :api_requests
  end
    
  resources :users do 
  resources :drawers
  end
  
  resources :drawers do 
  resources :drawer_ingredients
  end 
  
  resources :users do 
  resources :drawers do 
    get 'go_shopping'
  resources :recipes do
    get 'execute'
      end
    end
  end
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">

  <br><br><br>
  <hr />
  
Love <%= "Life".reverse! %> productions, 2017.

<br><br><br>

  
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Ingredients n' Recipes!", root_path, id: "logo" %><%= link_to ": More than just Ingredients!", root_path, id: "logo2" %>
    <nav>
      <ul class="nav navbar-nav navbar-right" style="padding-top: 6px;">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
            <% if logged_in? %>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Inventory", edit_user_drawer_path(current_user, current_user.drawers.first) %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ingredients n' Recipes!</title>
    <link href="https://fonts.googleapis.com/css?family=Dosis|Indie+Flower|Lobster" rel="stylesheet"> 
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      
 <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
  <%= render 'layouts/footer' %>
  
    </div>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="src/js/horizBarChart.js"></script>
  </body>
</html>